//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MironovLab.OpenVPN.Management {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MironovLab.OpenVPN.Management.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed with message: {0}.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot translate argument of type {0}.
        /// </summary>
        internal static string CommandArgumentTypeUnsupportedException {
            get {
                return ResourceManager.GetString("CommandArgumentTypeUnsupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected table name: {0}.
        /// </summary>
        internal static string CommandResultParsing_UnexpectedTableName {
            get {
                return ResourceManager.GetString("CommandResultParsing_UnexpectedTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address can be only IPv4 or IPv6 type.
        /// </summary>
        internal static string IPAddressRule_WrongAddressFamily {
            get {
                return ResourceManager.GetString("IPAddressRule_WrongAddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network can be only IPv4 or IPv6 type.
        /// </summary>
        internal static string IPNetworkRule_WrongAddressFamily {
            get {
                return ResourceManager.GetString("IPNetworkRule_WrongAddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server required management password to be passed. Please use method overload with password argument..
        /// </summary>
        internal static string ManagementPasswordRequired {
            get {
                return ResourceManager.GetString("ManagementPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected request for password didn&apos;t received.
        /// </summary>
        internal static string NoPasswordRequest {
            get {
                return ResourceManager.GetString("NoPasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enumerate more than one time.
        /// </summary>
        internal static string OneTimeEnumerable_CannotEnumerateTwice {
            get {
                return ResourceManager.GetString("OneTimeEnumerable_CannotEnumerateTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected.
        /// </summary>
        internal static string OvpnAlreadyConnected {
            get {
                return ResourceManager.GetString("OvpnAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid host name.
        /// </summary>
        internal static string OvpnManager_HostNameIsNotValid {
            get {
                return ResourceManager.GetString("OvpnManager_HostNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was not in a correct format..
        /// </summary>
        internal static string ParseFail {
            get {
                return ResourceManager.GetString("ParseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse line &quot;{0}&quot; using parser {1}.
        /// </summary>
        internal static string RealTimeMessageParsingException {
            get {
                return ResourceManager.GetString("RealTimeMessageParsingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message already set!.
        /// </summary>
        internal static string RTMessageParser_AlreadyParsed {
            get {
                return ResourceManager.GetString("RTMessageParser_AlreadyParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; does not support switch value &apos;{1}&apos;.
        /// </summary>
        internal static string SwitchEnumMemberIsNotSupported {
            get {
                return ResourceManager.GetString("SwitchEnumMemberIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header string passed is not a table header declaration!.
        /// </summary>
        internal static string TableReader_NotAHeader {
            get {
                return ResourceManager.GetString("TableReader_NotAHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row line passed is not a {0} table row line.
        /// </summary>
        internal static string TableReader_NotARow {
            get {
                return ResourceManager.GetString("TableReader_NotARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed row line is invalid: it contains different column count ({0}) than was declared in header ({1}).
        /// </summary>
        internal static string TableReader_RowHasInvalidColumnCount {
            get {
                return ResourceManager.GetString("TableReader_RowHasInvalidColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected command result: {0}.
        /// </summary>
        internal static string UnexpectedCommandResult {
            get {
                return ResourceManager.GetString("UnexpectedCommandResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbosity level allowed values range is between 0 and 15.
        /// </summary>
        internal static string VerbosityLevelOutOfRange {
            get {
                return ResourceManager.GetString("VerbosityLevelOutOfRange", resourceCulture);
            }
        }
    }
}
